# aks deploymen
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-springboot-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: my-springboot-app
          image: myspring.azurecr.io/saikrishnap123/springboot-sai:#{Build.BuildId}#
          imagePullPolicy: Always
          ports:
          - containerPort: 8085
          volumeMounts:
            - name: test-vol
              mountPath: "/etc/non-sensitive-data"
              readOnly: true

        
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-app
    k8s-app: springboot-app
  name: springboot-app
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8085
  type: LoadBalancer
  selector:
    app: springboot-app

