pool:
  name: Azure Pipelines
  demands: maven

steps:
- task: Maven@3
  displayName: 'Maven pom.xml'
  inputs:
    publishJUnitResults: false

- task: Docker@0
  displayName: 'Build an image'
  inputs:
    azureSubscription: 'Free Trial (eaa8dae0-e229-4aa5-841d-e2eb0ac76625)'
    azureContainerRegistry: '{"loginServer":"springyml.azurecr.io", "id" : "/subscriptions/eaa8dae0-e229-4aa5-841d-e2eb0ac76625/resourceGroups/aks-rg/providers/Microsoft.ContainerRegistry/registries/springyml"}'
    dockerFile: dockerfile
    includeLatestTag: true

- task: Docker@0
  displayName: 'Push an image'
  inputs:
    azureSubscription: 'Free Trial (eaa8dae0-e229-4aa5-841d-e2eb0ac76625)'
    azureContainerRegistry: '{"loginServer":"springyml.azurecr.io", "id" : "/subscriptions/eaa8dae0-e229-4aa5-841d-e2eb0ac76625/resourceGroups/aks-rg/providers/Microsoft.ContainerRegistry/registries/springyml"}'
    action: 'Push an image'
    includeLatestTag: true

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    Contents: 'aks-deploy-from-acr.yaml'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'


steps:
- task: qetza.replacetokens.replacetokens-task.replacetokens@5
  displayName: 'Replace tokens in aks-deploy-from-acr.yaml'
  inputs:
    rootDirectory: '$(System.DefaultWorkingDirectory)/_spring-petclinic-cicd-yaml-Docker container-CI/drop'
    targetFiles: 'aks-deploy-from-acr.yaml'
steps:
- task: Kubernetes@0
  displayName: 'kubectl apply'
  inputs:
    kubernetesServiceConnection: kubesvc1
    namespace: default
    command: apply
    useConfigurationFile: true
    configuration: '$(System.DefaultWorkingDirectory)/_spring-petclinic-cicd-yaml-Docker container-CI/drop/aks-deploy-from-acr.yaml'
